language: node_js
node_js:
  - "9"
dist: trusty
sudo: false
addons:
    chrome: stable
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
branches:
  except:
  - master
cache:
  directories:
    - node_modules
install:
  - npm install -g yarn
script:
  - yarn
  - yarn lint
  - yarn test
  - yarn e2e
  - yarn build --base-href https://raphaelbs.github.io/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
